version: "3.7"
services:

    eureka-serviceregistry:
        build: ./Eureka
        container_name: eureka-serviceregistry
        ports:
            - "8761:8761"
        tty: true

    zuul:
        build: ./ZuulAndFrontend
        container_name: zuul
        ports:
        - "8080:8083"
        environment:
            REGISTRY_HOST: eureka-serviceregistry
        tty: true
        depends_on:
            - eureka-serviceregistry
            - cars
            # - axon-server

    cars:
        build: ./Cars
        image: nikolabrodic/cars
        container_name: cars
        restart: on-failure
        # networks:
        #     - main-app-tls
        ports:
            - 8082:8082
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: rentacardb
        tty: true
        depends_on: 
            - mysql
            - eureka-serviceregistry
        #   - rabbitmq-broker
        #   - axon-server

    mysql:
        image: mysql:8.0.19
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: team29VJN
            MYSQL_USER: rentacar
            MYSQL_PASSWORD: RentACarTeam29
            MYSQL_DATABASE: rentacardb
        volumes:
            - mysql-data:/var/lib/mysql
    
    #   rabbitmq-broker:
    #     image: rabbitmq:management-alpine
    #     container_name: rabbitmq-broker
    #     ports:
    #       - 5672:5672
    #       - 5671:5671
    #       - 15671:15671
    #     networks:
    #       - main-app-tls
    #     environment:
    #       RABBITMQ_SSL_CACERTFILE: /etc/rabbitmq/cert/tls-ca-chain.pem
    #       RABBITMQ_SSL_CERTFILE: /etc/rabbitmq/cert/rabbitmq.crt
    #       RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
    #       RABBITMQ_SSL_KEYFILE: /etc/rabbitmq/cert/rabbitmq.key
    #       RABBITMQ_SSL_VERIFY: verify_peer
    #     volumes:
    #       - ./tls/certs/rabbitmq:/etc/rabbitmq/cert

volumes:
  mysql-data:
  logs:

# networks:
#   main-app-tls:
#     name: main-app-tls
#     driver: bridge
