version: "3.7"
services:
    eureka-serviceregistry:
        build: ./Eureka
        image: nikolabrodic/eureka-serviceregistry
        container_name: eureka-serviceregistry
        networks:
            - main-app-tls
        ports:
            - "8761:8761"
        environment:
            KEYSTORE: /etc/keystore/EUREKA_NAME.keystore.p12
            KEYSTORE_PASSWORD: EUREKA_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: EUREKA_ALIAS
            TRUSTSTORE: /etc/keystore/EUREKA_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: EUREKA_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
        volumes:
            - ./tls/certs/EUREKA_NAME/keystore:/etc/keystore
        depends_on:
            - rabbitmq-broker

    zuul:
        build: ./ZuulAndFrontend
        image: nikolabrodic/zuul
        container_name: zuul
        networks:
            - main-app-tls
        ports:
        - "8080:8080"
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            KEYSTORE: /etc/keystore/ZUUL_NAME.keystore.p12
            KEYSTORE_PASSWORD: ZUUL_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: ZUUL_ALIAS
            TRUSTSTORE: /etc/keystore/ZUUL_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: ZUUL_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
        volumes:
            - ./tls/certs/ZUUL_NAME/keystore:/etc/keystore
        depends_on:
            - eureka-serviceregistry
            - advertisements
            - cars
            - renting
            - users
            - search-service
            - rabbitmq-broker

    advertisements:
        build: ./Advertisements
        image: nikolabrodic/advertisements
        container_name: advertisements
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8081:8081
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mainapp-mysql
            DATABASE_SCHEMA: rentacardb
            KEYSTORE: /etc/keystore/ADVERTISEMENTS_NAME.keystore.p12
            KEYSTORE_PASSWORD: ADVERTISEMENTS_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: ADVERTISEMENTS_ALIAS
            TRUSTSTORE: /etc/keystore/ADVERTISEMENTS_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: ADVERTISEMENTS_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
        volumes:
            - ./tls/certs/ADVERTISEMENTS_NAME/keystore:/etc/keystore
        depends_on:
            - mainapp-mysql
            - eureka-serviceregistry
            - rabbitmq-broker

    cars:
        build: ./Cars
        image: nikolabrodic/cars
        container_name: cars
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8082:8082
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mainapp-mysql
            DATABASE_SCHEMA: rentacardb
            KEYSTORE: /etc/keystore/CARS_NAME.keystore.p12
            KEYSTORE_PASSWORD: CARS_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: CARS_ALIAS
            TRUSTSTORE: /etc/keystore/CARS_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: CARS_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
            UPLOADED_PICTURES_PATH: /etc/uploadedPictures/
        volumes:
            - ./tls/certs/CARS_NAME/keystore:/etc/keystore
            - ./uploadedPictures/:/etc/uploadedPictures/
        depends_on: 
            - mainapp-mysql
            - eureka-serviceregistry
            - rabbitmq-broker

    renting:
        build: ./Renting
        image: nikolabrodic/renting
        container_name: renting
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8083:8083
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mainapp-mysql
            DATABASE_SCHEMA: rentacardb
            KEYSTORE: /etc/keystore/RENTING_NAME.keystore.p12
            KEYSTORE_PASSWORD: RENTING_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: RENTING_ALIAS
            TRUSTSTORE: /etc/keystore/RENTING_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: RENTING_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
        volumes:
            - ./tls/certs/RENTING_NAME/keystore:/etc/keystore
        depends_on:
            - mainapp-mysql
            - eureka-serviceregistry
            - rabbitmq-broker

    users:
        build: ./Users
        image: nikolabrodic/users
        container_name: users
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8084:8084
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mainapp-mysql
            DATABASE_SCHEMA: rentacardb            
            KEYSTORE: /etc/keystore/USERS_NAME.keystore.p12
            KEYSTORE_PASSWORD: USERS_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: USERS_ALIAS
            TRUSTSTORE: /etc/keystore/USERS_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: USERS_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
        volumes:
            - ./tls/certs/USERS_NAME/keystore:/etc/keystore
        depends_on:
            - mainapp-mysql
            - eureka-serviceregistry
            - rabbitmq-broker

    search-service:
        build: ./SearchService
        image: nikolabrodic/search-service
        container_name: search-service
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8085:8085
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            DATABASE_USERNAME: search
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_SCHEMA: searchservicedb
            KEYSTORE: /etc/keystore/SEARCH_NAME.keystore.p12
            KEYSTORE_PASSWORD: SEARCH_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: SEARCH_ALIAS
            TRUSTSTORE: /etc/keystore/SEARCH_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: SEARCH_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
            H2_DB_PATH: /etc/h2-db-data
        volumes:
            - ./tls/certs/SEARCH_NAME/keystore:/etc/keystore
            - ./SearchService/src/main/resources/h2-db-data/:/etc/h2-db-data/
        depends_on:
            - eureka-serviceregistry
            - rabbitmq-broker

    logger:
        build: ./Logger
        image: nikolabrodic/logger
        container_name: logger
        restart: on-failure
        networks:
            - main-app-tls
        ports:
            - 8086:8086
        environment:
            REGISTRY_HOST: eureka-serviceregistry
            KEYSTORE: /etc/keystore/LOGGER_NAME.keystore.p12
            KEYSTORE_PASSWORD: LOGGER_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: LOGGER_ALIAS
            TRUSTSTORE: /etc/keystore/LOGGER_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: LOGGER_KEYSTORE_PASSWORD
            RMQ_HOST: rabbitmq-broker
            RMQ_PORT: 5671
            LOG_STORAGE: /var/log/mainapp-log-storage.log
            LOG_BACKUP_1: /var/log/mainapp-log-backup-1.log
            LOG_BACKUP_2: /var/log/mainapp-log-backup-2.log
        volumes:
            - ./tls/certs/LOGGER_NAME/keystore:/etc/keystore
            - mainapp-logs:/var/log
        depends_on:
            - eureka-serviceregistry
            - rabbitmq-broker

    mainapp-mysql:
        image: mysql:8.0.19
        container_name: mainapp-mysql
        restart: always
        networks:
            - main-app-tls
        environment:
            MYSQL_ROOT_PASSWORD: team29VJN
            MYSQL_USER: rentacar
            MYSQL_PASSWORD: RentACarTeam29
            MYSQL_DATABASE: rentacardb
        volumes:
            - mainapp-mysql-data:/var/lib/mysql
    
    rabbitmq-broker:
        image: rabbitmq:management-alpine
        container_name: rabbitmq-broker
        ports:
            - 5672:5672
            - 5671:5671
            - 15671:15671
        networks:
            - main-app-tls
        environment:
            RABBITMQ_SSL_CACERTFILE: /etc/rabbitmq/cert/tls-ca-chain.pem
            RABBITMQ_SSL_CERTFILE: /etc/rabbitmq/cert/RMQ_NAME.crt
            RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
            RABBITMQ_SSL_KEYFILE: /etc/rabbitmq/cert/RMQ_NAME.key
            RABBITMQ_SSL_VERIFY: verify_peer
        volumes:
            - ./tls/certs/RMQ_NAME:/etc/rabbitmq/cert

    agentapp:
        build: ./AgentApp
        image: jelenapopov/agentapp
        container_name: agentapp
        restart: on-failure
        networks:
            - agent-app-tls
        ports:
            - 8090:8090
        environment:
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: agentapp-mysql
            DATABASE_SCHEMA: agentappdb
            KEYSTORE: /etc/keystore/AGENT_APP_NAME.keystore.p12
            KEYSTORE_PASSWORD: AGENT_APP_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: AGENT_APP_ALIAS
            TRUSTSTORE: /etc/keystore/AGENT_APP_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: AGENT_APP_KEYSTORE_PASSWORD
            UPLOADED_PICTURES_PATH: /etc/uploadedPictures/
            LOG_STORAGE: /var/log/agentapp-log-storage.log
            LOG_BACKUP_1: /var/log/agentapp-log-backup-1.log
            LOG_BACKUP_2: /var/log/agentapp-log-backup-2.log
        volumes:
            - ./tls/certs/AGENT_APP_NAME/keystore:/etc/keystore
            - ./AgentApp/Backend/src/main/resources/uploadedPictures/:/etc/uploadedPictures/
            - agentapp-logs:/var/log
        depends_on: 
            - agentapp-mysql

    agentapp-mysql:
        image: mysql:8.0.19
        container_name: agentapp-mysql
        restart: always
        networks:
            - agent-app-tls
        environment:
            MYSQL_ROOT_PASSWORD: team29VJN
            MYSQL_USER: rentacar
            MYSQL_PASSWORD: RentACarTeam29
            MYSQL_DATABASE: agentappdb
        volumes:
            - agentapp-mysql-data:/var/lib/mysql
    
volumes:
    agentapp-mysql-data:
    mainapp-mysql-data:
    agentapp-logs:
    mainapp-logs:
    
networks:
    agent-app-tls:
        name: agent-app-tls
        driver: bridge
    main-app-tls:
        name: main-app-tls
        driver: bridge