//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 09:12:54 AM CEST 
//


package jvn.Advertisements.dto.soap.advertisement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="advertisementDetails" type="{http://www.soap.dto/advertisement}advertisementDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "advertisementDetails"
})
@XmlRootElement(name = "createOrEditAdvertisementDetailsResponse")
public class CreateOrEditAdvertisementDetailsResponse {

    @XmlElement(required = true)
    protected AdvertisementDetails advertisementDetails;

    /**
     * Gets the value of the advertisementDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdvertisementDetails }
     *     
     */
    public AdvertisementDetails getAdvertisementDetails() {
        return advertisementDetails;
    }

    /**
     * Sets the value of the advertisementDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvertisementDetails }
     *     
     */
    public void setAdvertisementDetails(AdvertisementDetails value) {
        this.advertisementDetails = value;
    }

}
