//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 05:02:18 PM CEST 
//


package jvn.RentACar.dto.soap.advertisement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="editPartialAdvertisementDetails" type="{http://www.soap.dto/advertisement}editPartialAdvertisementDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "email",
    "editPartialAdvertisementDetails"
})
@XmlRootElement(name = "editPartialAdvertisementDetailsRequest")
public class EditPartialAdvertisementDetailsRequest {

    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected EditPartialAdvertisementDetails editPartialAdvertisementDetails;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the editPartialAdvertisementDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EditPartialAdvertisementDetails }
     *     
     */
    public EditPartialAdvertisementDetails getEditPartialAdvertisementDetails() {
        return editPartialAdvertisementDetails;
    }

    /**
     * Sets the value of the editPartialAdvertisementDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditPartialAdvertisementDetails }
     *     
     */
    public void setEditPartialAdvertisementDetails(EditPartialAdvertisementDetails value) {
        this.editPartialAdvertisementDetails = value;
    }

}
