//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 05:02:18 PM CEST 
//


package jvn.RentACar.dto.soap.advertisement;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jvn.RentACar.dto.soap.advertisement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jvn.RentACar.dto.soap.advertisement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckIfCarIsAvailableRequest }
     * 
     */
    public CheckIfCarIsAvailableRequest createCheckIfCarIsAvailableRequest() {
        return new CheckIfCarIsAvailableRequest();
    }

    /**
     * Create an instance of {@link CheckIfCarIsAvailableResponse }
     * 
     */
    public CheckIfCarIsAvailableResponse createCheckIfCarIsAvailableResponse() {
        return new CheckIfCarIsAvailableResponse();
    }

    /**
     * Create an instance of {@link CreateOrEditAdvertisementDetailsRequest }
     * 
     */
    public CreateOrEditAdvertisementDetailsRequest createCreateOrEditAdvertisementDetailsRequest() {
        return new CreateOrEditAdvertisementDetailsRequest();
    }

    /**
     * Create an instance of {@link AdvertisementDetails }
     * 
     */
    public AdvertisementDetails createAdvertisementDetails() {
        return new AdvertisementDetails();
    }

    /**
     * Create an instance of {@link CreateOrEditAdvertisementDetailsResponse }
     * 
     */
    public CreateOrEditAdvertisementDetailsResponse createCreateOrEditAdvertisementDetailsResponse() {
        return new CreateOrEditAdvertisementDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementDetailsRequest }
     * 
     */
    public DeleteAdvertisementDetailsRequest createDeleteAdvertisementDetailsRequest() {
        return new DeleteAdvertisementDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteAdvertisementDetailsResponse }
     * 
     */
    public DeleteAdvertisementDetailsResponse createDeleteAdvertisementDetailsResponse() {
        return new DeleteAdvertisementDetailsResponse();
    }

    /**
     * Create an instance of {@link EditPartialAdvertisementDetailsRequest }
     * 
     */
    public EditPartialAdvertisementDetailsRequest createEditPartialAdvertisementDetailsRequest() {
        return new EditPartialAdvertisementDetailsRequest();
    }

    /**
     * Create an instance of {@link EditPartialAdvertisementDetails }
     * 
     */
    public EditPartialAdvertisementDetails createEditPartialAdvertisementDetails() {
        return new EditPartialAdvertisementDetails();
    }

    /**
     * Create an instance of {@link EditPartialAdvertisementDetailsResponse }
     * 
     */
    public EditPartialAdvertisementDetailsResponse createEditPartialAdvertisementDetailsResponse() {
        return new EditPartialAdvertisementDetailsResponse();
    }

    /**
     * Create an instance of {@link GetAdvertisementEditTypeRequest }
     * 
     */
    public GetAdvertisementEditTypeRequest createGetAdvertisementEditTypeRequest() {
        return new GetAdvertisementEditTypeRequest();
    }

    /**
     * Create an instance of {@link GetAdvertisementEditTypeResponse }
     * 
     */
    public GetAdvertisementEditTypeResponse createGetAdvertisementEditTypeResponse() {
        return new GetAdvertisementEditTypeResponse();
    }

    /**
     * Create an instance of {@link GetAllAdvertisementDetailsRequest }
     * 
     */
    public GetAllAdvertisementDetailsRequest createGetAllAdvertisementDetailsRequest() {
        return new GetAllAdvertisementDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllAdvertisementDetailsResponse }
     * 
     */
    public GetAllAdvertisementDetailsResponse createGetAllAdvertisementDetailsResponse() {
        return new GetAllAdvertisementDetailsResponse();
    }

}
