spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka-serviceregistry}
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

server:
  port: 8761

eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
