//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 09:14:40 PM CEST 
//


package jvn.RentACar.dto.soap.rentrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rentRequestDetails" type="{http://www.soap.dto/rentrequest}rentRequestDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rentRequestDetails"
})
@XmlRootElement(name = "createRentRequestResponse")
public class CreateRentRequestResponse {

    @XmlElement(required = true)
    protected RentRequestDetails rentRequestDetails;

    /**
     * Gets the value of the rentRequestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RentRequestDetails }
     *     
     */
    public RentRequestDetails getRentRequestDetails() {
        return rentRequestDetails;
    }

    /**
     * Sets the value of the rentRequestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RentRequestDetails }
     *     
     */
    public void setRentRequestDetails(RentRequestDetails value) {
        this.rentRequestDetails = value;
    }

}
