//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 09:14:40 PM CEST 
//


package jvn.RentACar.dto.soap.rentrequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jvn.RentACar.dto.soap.rentrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jvn.RentACar.dto.soap.rentrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeRentRequestStatusRequest }
     * 
     */
    public ChangeRentRequestStatusRequest createChangeRentRequestStatusRequest() {
        return new ChangeRentRequestStatusRequest();
    }

    /**
     * Create an instance of {@link ChangeRentRequestStatusResponse }
     * 
     */
    public ChangeRentRequestStatusResponse createChangeRentRequestStatusResponse() {
        return new ChangeRentRequestStatusResponse();
    }

    /**
     * Create an instance of {@link CheckDateRequest }
     * 
     */
    public CheckDateRequest createCheckDateRequest() {
        return new CheckDateRequest();
    }

    /**
     * Create an instance of {@link CheckDateResponse }
     * 
     */
    public CheckDateResponse createCheckDateResponse() {
        return new CheckDateResponse();
    }

    /**
     * Create an instance of {@link CheckIfCanAcceptRequest }
     * 
     */
    public CheckIfCanAcceptRequest createCheckIfCanAcceptRequest() {
        return new CheckIfCanAcceptRequest();
    }

    /**
     * Create an instance of {@link CheckIfCanAcceptResponse }
     * 
     */
    public CheckIfCanAcceptResponse createCheckIfCanAcceptResponse() {
        return new CheckIfCanAcceptResponse();
    }

    /**
     * Create an instance of {@link HasDebtRequest }
     * 
     */
    public HasDebtRequest createHasDebtRequest() {
        return new HasDebtRequest();
    }

    /**
     * Create an instance of {@link HasDebtResponse }
     * 
     */
    public HasDebtResponse createHasDebtResponse() {
        return new HasDebtResponse();
    }

    /**
     * Create an instance of {@link GetAllRentRequestDetailsRequest }
     * 
     */
    public GetAllRentRequestDetailsRequest createGetAllRentRequestDetailsRequest() {
        return new GetAllRentRequestDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllRentRequestDetailsResponse }
     * 
     */
    public GetAllRentRequestDetailsResponse createGetAllRentRequestDetailsResponse() {
        return new GetAllRentRequestDetailsResponse();
    }

    /**
     * Create an instance of {@link RentRequestDetails }
     * 
     */
    public RentRequestDetails createRentRequestDetails() {
        return new RentRequestDetails();
    }

    /**
     * Create an instance of {@link PaidRentInfoRequest }
     * 
     */
    public PaidRentInfoRequest createPaidRentInfoRequest() {
        return new PaidRentInfoRequest();
    }

    /**
     * Create an instance of {@link PaidRentInfoResponse }
     * 
     */
    public PaidRentInfoResponse createPaidRentInfoResponse() {
        return new PaidRentInfoResponse();
    }

    /**
     * Create an instance of {@link CreateRentRequestRequest }
     * 
     */
    public CreateRentRequestRequest createCreateRentRequestRequest() {
        return new CreateRentRequestRequest();
    }

    /**
     * Create an instance of {@link CreateRentRequestResponse }
     * 
     */
    public CreateRentRequestResponse createCreateRentRequestResponse() {
        return new CreateRentRequestResponse();
    }

    /**
     * Create an instance of {@link RentInfoDetails }
     * 
     */
    public RentInfoDetails createRentInfoDetails() {
        return new RentInfoDetails();
    }

    /**
     * Create an instance of {@link MessageDetails }
     * 
     */
    public MessageDetails createMessageDetails() {
        return new MessageDetails();
    }

    /**
     * Create an instance of {@link CommentDetails }
     * 
     */
    public CommentDetails createCommentDetails() {
        return new CommentDetails();
    }

}
