//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 10:22:04 PM CEST 
//


package jvn.RentACar.dto.soap.rentrequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jvn.RentACar.dto.soap.rentrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jvn.RentACar.dto.soap.rentrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateRentRequestRequest }
     * 
     */
    public CreateRentRequestRequest createCreateRentRequestRequest() {
        return new CreateRentRequestRequest();
    }

    /**
     * Create an instance of {@link RentRequestDetails }
     * 
     */
    public RentRequestDetails createRentRequestDetails() {
        return new RentRequestDetails();
    }

    /**
     * Create an instance of {@link CreateRentRequestResponse }
     * 
     */
    public CreateRentRequestResponse createCreateRentRequestResponse() {
        return new CreateRentRequestResponse();
    }

    /**
     * Create an instance of {@link CommentDetails }
     * 
     */
    public CommentDetails createCommentDetails() {
        return new CommentDetails();
    }

    /**
     * Create an instance of {@link RentInfoDetails }
     * 
     */
    public RentInfoDetails createRentInfoDetails() {
        return new RentInfoDetails();
    }

    /**
     * Create an instance of {@link MessageDetails }
     * 
     */
    public MessageDetails createMessageDetails() {
        return new MessageDetails();
    }

}
