export const environment = {
  production: true,
  baseUrl: "http://localhost:8080",
  advertisement: "/advertisements/api/advertisement",
  bodyStyle: "/cars/api/body-style",
  fuelType: "/cars/api/fuel-type",
  gearBoxType: "/cars/api/gearbox-type",
  car: "/cars/api/car",
  priceList: "/advertisements/api/price-list",
  client: "/users/api/client",
  rentRequest: "/renting/api/rent-request",
  socket: "/renting",
  auth: "/users/api/auth",
  agent: "/users/api/agent",
  admin: "/users/api/admin",
  make: "/cars/api/make",
  model: "/cars/api/model",
  message: "/renting/api/message",
  comment: "/renting/api/comment",
  rentReport: "/renting/api/rent-report",
  role: "/users/api/role",
  permission: "/users/api/permission",
  searchAdvertisements: "/search/api/advertisement",
};
