export const environment = {
  production: true,
  baseUrl: 'https://localhost:8080',
  advertisement: '/api/advertisement',
  bodyStyle: '/api/body-style',
  fuelType: '/api/fuel-type',
  gearBoxType: '/api/gearbox-type',
  car: '/api/car',
  priceList: '/api/price-list',
  client: '/api/client',
  rentRequest: '/api/rent-request',
  auth: '/api/auth',
  agent: '/api/agent',
  admin: '/api/admin',
  make: "/api/make",
  model: "/api/model",
  message: "/api/message",
  comment: '/api/comment',
  rentReport: "/api/rent-report",
  role: "/api/role",
  permission: "/api/permission",
};
