//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 12:37:06 AM CEST 
//


package jvn.RentACar.dto.soap.agent;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jvn.RentACar.dto.soap.agent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jvn.RentACar.dto.soap.agent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgentDetailsRequest }
     * 
     */
    public GetAgentDetailsRequest createGetAgentDetailsRequest() {
        return new GetAgentDetailsRequest();
    }

    /**
     * Create an instance of {@link AgentDetails }
     * 
     */
    public AgentDetails createAgentDetails() {
        return new AgentDetails();
    }

    /**
     * Create an instance of {@link GetAgentDetailsResponse }
     * 
     */
    public GetAgentDetailsResponse createGetAgentDetailsResponse() {
        return new GetAgentDetailsResponse();
    }

    /**
     * Create an instance of {@link GetProfileAgentDetailsRequest }
     * 
     */
    public GetProfileAgentDetailsRequest createGetProfileAgentDetailsRequest() {
        return new GetProfileAgentDetailsRequest();
    }

    /**
     * Create an instance of {@link GetProfileAgentDetailsResponse }
     * 
     */
    public GetProfileAgentDetailsResponse createGetProfileAgentDetailsResponse() {
        return new GetProfileAgentDetailsResponse();
    }

}
