//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:23:47 PM CEST 
//


package jvn.Renting.dto.soap.comment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rentRequestId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rentInfoId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="commentDetails" type="{http://www.soap.dto/comment}commentDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "email",
    "rentRequestId",
    "rentInfoId",
    "commentDetails"
})
@XmlRootElement(name = "createCommentRequest")
public class CreateCommentRequest {

    @XmlElement(required = true)
    protected String email;
    protected long rentRequestId;
    protected long rentInfoId;
    @XmlElement(required = true)
    protected CommentDetails commentDetails;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the rentRequestId property.
     * 
     */
    public long getRentRequestId() {
        return rentRequestId;
    }

    /**
     * Sets the value of the rentRequestId property.
     * 
     */
    public void setRentRequestId(long value) {
        this.rentRequestId = value;
    }

    /**
     * Gets the value of the rentInfoId property.
     * 
     */
    public long getRentInfoId() {
        return rentInfoId;
    }

    /**
     * Sets the value of the rentInfoId property.
     * 
     */
    public void setRentInfoId(long value) {
        this.rentInfoId = value;
    }

    /**
     * Gets the value of the commentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CommentDetails }
     *     
     */
    public CommentDetails getCommentDetails() {
        return commentDetails;
    }

    /**
     * Sets the value of the commentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentDetails }
     *     
     */
    public void setCommentDetails(CommentDetails value) {
        this.commentDetails = value;
    }

}
