//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:23:47 PM CEST 
//


package jvn.Renting.dto.soap.comment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commentDetails" type="{http://www.soap.dto/comment}commentDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commentDetails"
})
@XmlRootElement(name = "createCommentResponse")
public class CreateCommentResponse {

    @XmlElement(required = true)
    protected CommentDetails commentDetails;

    /**
     * Gets the value of the commentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CommentDetails }
     *     
     */
    public CommentDetails getCommentDetails() {
        return commentDetails;
    }

    /**
     * Sets the value of the commentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentDetails }
     *     
     */
    public void setCommentDetails(CommentDetails value) {
        this.commentDetails = value;
    }

}
