//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:24:23 PM CEST 
//


package jvn.Renting.dto.soap.comment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="leaveFeedbackDetails" type="{http://www.soap.dto/comment}leaveFeedbackDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "leaveFeedbackDetails"
})
@XmlRootElement(name = "leaveFeedbackResponse")
public class LeaveFeedbackResponse {

    @XmlElement(required = true)
    protected LeaveFeedbackDetails leaveFeedbackDetails;

    /**
     * Gets the value of the leaveFeedbackDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LeaveFeedbackDetails }
     *     
     */
    public LeaveFeedbackDetails getLeaveFeedbackDetails() {
        return leaveFeedbackDetails;
    }

    /**
     * Sets the value of the leaveFeedbackDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeaveFeedbackDetails }
     *     
     */
    public void setLeaveFeedbackDetails(LeaveFeedbackDetails value) {
        this.leaveFeedbackDetails = value;
    }

}
