//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 10:28:30 PM CEST 
//


package jvn.Renting.dto.soap.comment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jvn.Renting.dto.soap.comment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jvn.Renting.dto.soap.comment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckIfCanCommentRequest }
     * 
     */
    public CheckIfCanCommentRequest createCheckIfCanCommentRequest() {
        return new CheckIfCanCommentRequest();
    }

    /**
     * Create an instance of {@link CheckIfCanCommentResponse }
     * 
     */
    public CheckIfCanCommentResponse createCheckIfCanCommentResponse() {
        return new CheckIfCanCommentResponse();
    }

    /**
     * Create an instance of {@link CreateCommentRequest }
     *
     */
    public CreateCommentRequest createCreateCommentRequest() {
        return new CreateCommentRequest();
    }

    /**
     * Create an instance of {@link CreateCommentResponse }
     *
     */
    public CreateCommentResponse createCreateCommentResponse() {
        return new CreateCommentResponse();
    }

    /**
     * Create an instance of {@link GetAllCommentsDetailsRequest }
     *
     */
    public GetAllCommentsDetailsRequest createGetAllCommentsDetailsRequest() {
        return new GetAllCommentsDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllCommentsDetailsResponse }
     *
     */
    public GetAllCommentsDetailsResponse createGetAllCommentsDetailsResponse() {
        return new GetAllCommentsDetailsResponse();
    }

    /**
     * Create an instance of {@link GetFeedbackDetailsRequest }
     *
     */
    public GetFeedbackDetailsRequest createGetFeedbackDetailsRequest() {
        return new GetFeedbackDetailsRequest();
    }

    /**
     * Create an instance of {@link GetFeedbackDetailsResponse }
     *
     */
    public GetFeedbackDetailsResponse createGetFeedbackDetailsResponse() {
        return new GetFeedbackDetailsResponse();
    }

    /**
     * Create an instance of {@link LeaveFeedbackRequest }
     *
     */
    public LeaveFeedbackRequest createLeaveFeedbackRequest() {
        return new LeaveFeedbackRequest();
    }

    /**
     * Create an instance of {@link LeaveFeedbackResponse }
     *
     */
    public LeaveFeedbackResponse createLeaveFeedbackResponse() {
        return new LeaveFeedbackResponse();
    }

    /**
     * Create an instance of {@link CommentDetails }
     *
     */
    public CommentDetails createCommentDetails() {
        return new CommentDetails();
    }

    /**
     * Create an instance of {@link FeedbackDetails }
     *
     */
    public FeedbackDetails createFeedbackDetails() {
        return new FeedbackDetails();
    }

    /**
     * Create an instance of {@link LeaveFeedbackDetails }
     *
     */
    public LeaveFeedbackDetails createLeaveFeedbackDetails() {
        return new LeaveFeedbackDetails();
    }

}
