version: "3.7"
services:
    agentapp:
        build: .
        image: jelenapopov/agentapp
        container_name: agentapp
        restart: on-failure
        networks:
            - agent-app-tls
        ports:
            - 8090:8080
        environment:
            DATABASE_USERNAME: rentacar
            DATABASE_PASSWORD: RentACarTeam29
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: agentappdb
            KEYSTORE: /etc/keystore/AGENT_APP_NAME.keystore.p12
            KEYSTORE_PASSWORD: AGENT_APP_KEYSTORE_PASSWORD
            KEYSTORE_ALIAS: AGENT_APP_ALIAS
            TRUSTSTORE: /etc/keystore/AGENT_APP_NAME.truststore.p12
            TRUSTSTORE_PASSWORD: AGENT_APP_KEYSTORE_PASSWORD
        #     RMQ_HOST: rabbitmq-broker
        #     RMQ_PORT: 5671
        volumes:
            - ./tls/certs/AGENT_APP_NAME/keystore:/etc/keystore
        depends_on: 
            - mysql
            # - rabbitmq-broker
    mysql:
        image: mysql:8.0.19
        container_name: mysql
        restart: always
        networks:
            - agent-app-tls
        environment:
            MYSQL_ROOT_PASSWORD: team29VJN
            MYSQL_USER: rentacar
            MYSQL_PASSWORD: RentACarTeam29
            MYSQL_DATABASE: agentappdb
        volumes:
            - mysql-data:/var/lib/mysql       
volumes:
    mysql-data:
    logs:
    
networks:
    agent-app-tls:
        name: agent-app-tls
        driver: bridge