//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 10:55:58 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soap.dto/client", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jvn.RentACar.dto.soap.client;
